[package]
name = "liblivephoto-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
liblivephoto = { path = "../crates/liblivephoto" }
liblivephoto-format = { path = "../crates/liblivephoto-format" }

[workspace]
members = ["."]

[[bin]]
name = "asset_input"
path = "fuzz_targets/asset_input.rs"
test = false
doc = false
bench = false

[[bin]]
name = "container_headers"
path = "fuzz_targets/container_headers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "remux"
path = "fuzz_targets/remux.rs"
test = false
doc = false
bench = false
